# Generated by Django 5.1 on 2024-09-15 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_rename_is_admin_user_is_staff_user_date_joined'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
