# Generated by Django 5.1.2 on 2024-10-22 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('indicators', '0005_userapikey'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationIndicator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transformation', models.CharField(choices=[('square', 'x²'), ('identity', 'x'), ('sqrt', '√x'), ('log', 'ln(x)'), ('neg_sqrt_reciprocal', '-1/√x'), ('neg_reciprocal', '-1/x'), ('neg_square_reciprocal', '-1/x²')], max_length=25)),
                ('indicator', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='indicators.indicator')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('indicator', 'transformation'), name='unique_indicator_transformation')],
            },
        ),
    ]
