# Generated by Django 5.1.2 on 2024-10-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Valuation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('value', models.FloatField()),
            ],
        ),
    ]
