# Generated by Django 5.1.2 on 2024-10-31 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0003_valuationindicator_color_valuationindicator_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AddIndex(
            model_name='valuation',
            index=models.Index(fields=['date'], name='valuation_v_date_3177c7_idx'),
        ),
    ]
