# Generated by Django 5.1.2 on 2026-03-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valuation', '0004_alter_valuation_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valuation',
            name='date',
            field=models.DateField(db_index=True, unique=True),
        ),
    ]
