# Generated by Django 5.1 on 2024-09-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0003_datasource_datasourcevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='datasource',
            name='url',
            field=models.CharField(default='temp', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datasource',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
