# Generated by Django 5.1.2 on 2026-03-26 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0005_userapikey'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicatorvalue',
            unique_together={('indicator', 'date')},
        ),
    ]
