# Generated by Django 5.1.2 on 2026-03-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0006_alter_indicatorvalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitcoinprice',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
