# Generated by Django 5.1.2 on 2026-03-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicators', '0007_alter_bitcoinprice_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datasource',
            name='url',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='datasourcevalue',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='indicator',
            name='url_name',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='indicatorvalue',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
