# Generated by Django 5.1 on 2024-09-03 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='value',
            field=models.IntegerField(),
        ),
    ]
