# Generated by Django 5.1 on 2024-09-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity', '0002_alter_series_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastUpdated',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
