# Generated by Django 5.1.2 on 2026-03-26 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('liquidity', '0003_lastupdated'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='series',
            unique_together={('ticker', 'date')},
        ),
    ]
